"Docs: links check":
  stage: test
  script:
    - cd docs && make linkcheck
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: ($CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH) || ($CI_PIPELINE_SOURCE == "merge_request_event")
      allow_failure: true
    - when: on_success